dav_ext_lock_zone zone=dav:10m;

server {
	listen *:443 ssl;
	server_name dav;
	access_log /var/log/nginx/dav.access.log;
	error_log /var/log/nginx/dav.error.log warn;

	include "/usr/local/etc/nginx/hostname_ssl.conf";

	location /dav {
		proxy_pass http://unix:/var/imap/socket/http:;
	}
}

server {
	listen *:80;
	server_name dav;
	access_log /var/log/nginx/dav.access.log;
	error_log /var/log/nginx/dav.error.log warn;

	include "/usr/local/etc/nginx/le_webroot.conf";
}
