server {
	listen 127.0.0.1:80 default accept_filter=httpready so_keepalive=on reuseport;
	access_log /var/log/nginx/stub_status.access.log;
	error_log /var/log/nginx/stub_status.error.log;

	location = /stub_status {
		stub_status on;
	}
}
