Domain			domain
Selector		some
Socket			local:/var/db/dkim/opendkim.socket
Syslog			Yes
KeyTable		/var/db/dkim/KeyTable
SigningTable	refile:/var/db/dkim/SigningTable
ExternalIgnoreList	refile:/var/db/dkim/TrustedHosts
InternalHosts	refile:/var/db/dkim/TrustedHosts
RequireSafeKeys	False
