include "/usr/local/etc/namedb/logging.conf";
include "/usr/local/etc/namedb/acls.conf";

//http local-http-server {
	//endpoints { "/dns-query"; };
//};

options {
	directory	"/usr/local/etc/namedb/working";
	pid-file	"/var/run/named/pid";
	dump-file	"/var/dump/named_dump.db";
	statistics-file	"/var/stats/named.stats";

	memstatistics-file "/var/stats/named.memstats";
	zone-statistics yes;
	allow-transfer { xfer; };

	listen-on { any; };
	//listen-on port 5380 tls none http local-http-server { any; };

	listen-on-v6	{ any; };
	//listen-on-v6 port 5380 tls none http local-http-server { any; };

	disable-empty-zone "255.255.255.255.IN-ADDR.ARPA";
	disable-empty-zone "0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.IP6.ARPA";
	disable-empty-zone "1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.IP6.ARPA";

	edns-udp-size 1232;
	max-udp-size 1232;
};

view "restricted" {
	match-clients { restricted;};
	recursion yes;

	//include "/usr/local/etc/namedb/local.conf";
	include "/usr/local/etc/namedb/master.conf";
	include "/usr/local/etc/namedb/generic.conf";
	//include "/usr/local/etc/namedb/slave_internal.conf";
	//include "/usr/local/etc/namedb/restricted.conf";

	//include "/usr/local/etc/namedb/ads.conf";
};

view "internal" {
	match-clients { trusted; inside; };
	recursion yes;

	include "/usr/local/etc/namedb/local.conf";
	#include "/usr/local/etc/namedb/master.conf";
	include "/usr/local/etc/namedb/generic.conf";
	//include "/usr/local/etc/namedb/slave_internal.conf";

	include "/usr/local/etc/namedb/ads.conf";
};

view "external-chaos" chaos {
	match-clients { any; };
	recursion no;

	zone "." { type hint; file "/dev/null"; };
	zone "bind" { type master; file "/usr/local/etc/namedb/master/bind.db"; allow-transfer { none; }; };
};

view "default" {
	match-clients { any; };
	recursion no;

	include "/usr/local/etc/namedb/master.conf";
	include "/usr/local/etc/namedb/generic.conf";
};
