#!/bin/sh
# vi:ft=sh:

# silence
daily_local=
weekly_local=
monthly_local=

# hourly

hourly_show_badconfig=yes
hourly_show_success=no

# security
security_show_badconfig=yes
security_show_success=no
security_show_info=no

security_status_passwdless_enable=no
security_status_pfdenied_enable=no
security_status_loginfail_enable=no

# daily
daily_show_success=no
daily_show_badconfig=yes
daily_show_info=no

daily_accounting_compress=yes
#daily_accounting_enable=no
daily_calendar_enable=yes
daily_clean_disks_enable=yes
daily_clean_disks_files=",* .#* a.out *.core *.CKP .emacs_[0-9]*"
#daily_clean_hoststat_enable=no # sendmail
daily_clean_tmps_enable=yes
daily_clean_tmps_verbose=no
daily_scrub_zfs_enable=yes
#daily_status_mail_rejects_enable=no
daily_status_ntpd_enable=yes
#daily_status_include_submit_mailq=no # sendmail

daily_status_uptime_enable=no
daily_status_zfs_enable=yes
daily_queuerun_enable=no

# weekly
weekly_show_badconfig=yes
weekly_show_success=no
weekly_show_info=no

weekly_noid_enable=yes

# monthly
monthly_show_badconfig=yes
monthly_show_success=no
monthly_show_info=no

# port
monthly_statistics_enable=yes
monthly_statistics_report_devices=yes
monthly_statistics_report_ports=yes

# ports-mgmt/pkg
daily_backup_pkg_enable=yes
daily_status_pkg_changes_enable=yes

weekly_status_pkg_enable=yes

if [ -r /etc/periodic.local ]; then
  . /etc/periodic.local
fi
