# screen like key
set-option -g prefix ^a
unbind-key C-b
bind-key ^a send-prefix

set -g status-position top
set -g escape-time 10
set -g default-terminal tmux-256color
set-option -g focus-events on
#set-option -g mouse on
set-option -sa terminal-overrides ',xterm*:RGB:Tc'

#set -g status-interval 2
#set -g status-left "[#S] #[fg=green,bg=black]#(tmux-mem-cpu-load --colors --interval 2)#[default] "
#set -g status-left-length 60

bind-key -n Home send Escape "OH"
bind-key -n End send Escape "OF"

set-option -g set-titles on

set-option -g history-limit 2000

# use Tab instead of l
bind-key Tab last-window
unbind-key l

bind-key Z set remain-on-exit
bind-key z respawn-pane

#### COLOUR (Solarized dark)

# default statusbar colors
set-option -g status-bg black #base02
set-option -g status-fg yellow #yellow
set-option -g status-style default

# default window title colors
set-window-option -g window-status-style fg=brightblue,bg=default

# active window title colors
set-window-option -g window-status-current-style fg=brightred,bg=default

# pane border
set-option -g pane-border-style fg=black #base02
set-option -g pane-active-border-style fg=brightgreen #base01

# message text
set-option -g message-style fg=brightred,bg=black

# pane number display
set-option -g display-panes-active-colour blue #blue
set-option -g display-panes-colour brightred #orange

# clock
set-window-option -g clock-mode-colour green #green

#### COLOUR (Selenized dark)

# default statusbar colors
set-option -g status-bg '#103c48'
set-option -g status-fg '#adbcbc'
set-option -g status-style default

# default window title colors
set-window-option -g window-status-style fg='#cad8d9',bg='#2d5b69'

# active window title colors
set-window-option -g window-status-current-style fg='#cad8d9',bg='#2d5b69'

# pane border
set-option -g pane-border-style fg='#184956'
set-option -g pane-active-border-style fg='#84c747'

# message text
set-option -g message-style fg='#ff665c',bg='#184956'

# pane number display
set-option -g display-panes-active-colour '#4695f7'
set-option -g display-panes-colour '#ff665c'

# clock
set-window-option -g clock-mode-colour '#75b938'
