#
log-facility local7;
authoritative;
ddns-updates off;
ddns-update-style interim;
ddns-domainname "domain.lan";
ddns-rev-domainname "in-addr.arpa";

zone domain.lan. {
	primary 127.0.0.1;
	key DHCP_UPDATER;
}
