max_connections = 100
shared_buffers = 128MB
dynamic_shared_memory_type = posix
max_wal_size = 1GB
min_wal_size = 80MB
log_destination = 'syslog'
log_timezone = 'Europe/Kiev'
update_process_title = off
datestyle = 'iso, dmy'
timezone = 'Europe/Kiev'
lc_messages = 'en_US.UTF-8'
lc_monetary = 'uk_UA.UTF-8'
lc_numeric = 'uk_UA.UTF-8'
lc_time = 'uk_UA.UTF-8'
default_text_search_config = 'pg_catalog.simple'
listen_addresses = '*'
#ssl = on
shared_preload_libraries = 'vchord'
log_min_duration_statement = 1000
default_toast_compression = 'lz4'
