START {
	recover	cmd="ctl_cyrusdb -r"
}

SERVICES {
	imap		cmd="imapd" listen="imap" prefork=0
	imaps		cmd="imapd -s" listen="imaps" prefork=1
	sieve		cmd="timsieved" listen="sieve" prefork=0
	lmtpunix	cmd="lmtpd" listen="/var/imap/socket/lmtp" prefork=0
	httpd		cmd="httpd" listen="/var/imap/socket/http" prefork=1 maxchild=20
}

EVENTS {
	checkpoint	cmd="ctl_cyrusdb -c" period=30
	delprune	cmd="cyr_expire -E 356d -D 3d -X 3d" at=0400
	ipurge		cmd="ipurge -f -o -d 31" at=0200
	tlsprune	cmd="tls_prune" at=0410
}

DAEMON {
	idled		cmd="idled"
	#squatter	cmd="squatter -R"
}
