#
admins: cyrus
allowplaintext: yes
altnamespace: no
anysievefolder: yes
autocreate_quota: 1048576
conversations: 1
configdirectory: /var/imap
defaultdomain: some.domain
hashimapspool: true
httpmodules: admin caldav carddav domainkey freebusy ischedule webdav
lmtpsocket: /var/imap/socket/lmtp
#maxlogins_per_user: 5
partition-default: /var/spool/imap
partition-news: /var/spool/news
sasl_minimum_layer: 0
sasl_pwcheck_method: saslauthd
search_engine: squat
sieve_allowplaintext: yes
sieveusehomedir: yes
statuscache: yes
sync_log: on
sync_log_channels: squatter
syslog_facility: news
tcp_keepalive: 1

tls_ciphers: HIGH

openio_verbosity: debug
